//user reducer types
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER'

//restaurant reducer types 
export const LOGIN_RESTAURANT = 'LOGIN_RESTAURANT'
export const SIGNUP_RESTAURANT = 'SIGNUP_RESTAURANT'
export const GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS'
export const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA'
export const EDIT_RESTAURANT_PROFILE = 'EDIT_RESTAURANT_PROFILE'
